[
  {
    "tipo": "Urbano",
    "matricula": "155",
    "setor": "0003",
    "quadra": "0012",
    "lote": "0010",
    "nomefrente": "c",
    "medidafrente": "10",
    "nomefundo": "f",
    "medidafundo": "12",
    "nomeesquerdo": "s",
    "medidaEsquerda": "7",
    "nomeDireito": "d",
    "medidadireito": "3",
    "areatotalimovel": "55",
    "endereco": "avenida medidci",
    "numero": "55",
    "bairro": "centro",
    "cep": "36.390-000",
    "cidade": "Lagoa dos Patos",
    "estado": "MG"
  },
  {
    "tipo": "Urbano",
    "matricula": "1033",
    "partecompleto": "de um lote",
    "setor": "0003",
    "quadra": "0005",
    "lote": "015B",
    "nomefrente": "fer",
    "medidafrente": "8",
    "nomefundo": "ffdsaf",
    "medidafundo": "8.36",
    "nomeesquerdo": "esq",
    "medidaEsquerda": "18.55",
    "nomeDireito": "die",
    "medidadireito": "13.65",
    "areatotalimovel": "132",
    "endereco": "avenida medidci",
    "numero": "55",
    "bairro": "centro",
    "cep": "36.390-000",
    "cidade": "Lagoa dos Patos",
    "estado": "MG"
  },
  {
    "id": 3,
    "tipo": "Rural",
    "matricula": "registrado",
    "registrodia": "07",
    "registromei": "06",
    "registroAno": "2010",
    "setor": "",
    "denominacao": "Sendo adquirida escritura pública de partilha amigável.",
    "quadra": "",
    "lote": "",
    "nomefrente": "frente rural",
    "medidafrente": "40",
    "nomefundo": "fundo rural",
    "medidafundo": "40",
    "nomeesquerdo": "esquerdo rural",
    "medidaEsquerda": "70",
    "nomeDireito": "direito rural",
    "medidadireito": "70",
    "areatotalimovel": "2800",
    "endereco": "campo alegre",
    "numero": "S/N",
    "bairro": "fazenda foqueirão",
    "cep": "39.360-000",
    "cidade": "Lagoa dos Patos",
    "estado": "MG"
  },
  {
    "id": 4,
    "tipo": "Rural",
    "matricula": "1025",
    "registrodia": "10",
    "registromei": "05",
    "registroAno": "2023",
    "setor": "",
    "denominacao": "",
    "quadra": "",
    "lote": "",
    "nomefrente": "ff",
    "medidafrente": "40",
    "nomefundo": "ff",
    "medidafundo": "40",
    "nomeesquerdo": "fff",
    "medidaEsquerda": "60",
    "nomeDireito": "fff",
    "medidadireito": "60",
    "areatotalimovel": "2400",
    "endereco": "rua jk",
    "numero": "235",
    "bairro": "vila branca",
    "cep": "39360-000",
    "cidade": "Lagoa dos Patos",
    "estado": "MG"
  }
]
